{{- if and .Values.stack.deploy .Values.xchem.host }}
---
kind: Secret
apiVersion: v1
metadata:
  name: xchem
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fragalysis-stack.labels" . | nindent 4 }}
stringData:
  user: {{ .Values.xchem.user | quote }}
  password: {{ .Values.xchem.password | quote }}
  name: {{ .Values.xchem.name | quote }}
  host: {{ .Values.xchem.host | quote }}
  port: {{ .Values.xchem.port | quote }}
{{- end }}
