{{- if or .Values.backups.database.rcloneBucketAndPath .Values.backups.media.rcloneBucket }}
---
kind: Secret
apiVersion: v1
metadata:
  name: backup-rclone
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fragalysis-stack.labels" . | nindent 4 }}
stringData:
  s3_endpoint: {{ .Values.backups.rclone.s3Endpoint | quote }}
  s3_provider: {{ .Values.backups.rclone.s3Provider | quote }}
  s3_access_key_id: {{ .Values.backups.rclone.s3AccessKeyId | quote }}
  s3_secret_access_key: {{ .Values.backups.rclone.s3SecretAccessKey | quote }}
  s3_default_region: {{ .Values.backups.rclone.s3DefaultRegion | quote }}
{{- end }}
