{{- if .Values.backups.database.rsync.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: backup-rsync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fragalysis-stack.labels" . | nindent 4 }}
stringData:
  host: {{ .Values.backups.database.rsync.host | quote }}
  path: {{ .Values.backups.database.rsync.path | quote }}
  user: {{ .Values.backups.database.rsync.user | quote }}
  pass: {{ .Values.backups.database.rsync.pass | quote }}
{{- end }}
