---
apiVersion: v2
name: fragalysis-stack
description: >-
  The Fragalysis Stack - a Django web application with its Celery worker
  and beat Pods, PostgreSQL, pgBouncer, Redis and optional backups
type: application
version: 0.1.0
home: https://github.com/xchem/fragalysis-helm
sources:
- https://github.com/xchem/fragalysis-helm
- https://github.com/xchem/fragalysis-stack
keywords:
- fragalysis
- xchem
