{{- with .Values.ssh.privateKey }}
---
kind: Secret
apiVersion: v1
metadata:
  name: ssh-key
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ta-authenticator.labels" $ | nindent 4 }}
stringData:
  fragalysis-stack-ssh-key: |
    {{- . | trimSuffix "\n" | nindent 4 }}
{{- end }}
