---
kind: Secret
apiVersion: v1
metadata:
  name: keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ta-authenticator.labels" . | nindent 4 }}
stringData:
  query_key: {{ .Values.queryKey | quote }}
  stats_key: {{ .Values.statsKey | quote }}
