---
kind: Service
apiVersion: v1
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
  labels:
    name: auth
    {{- include "ta-authenticator.labels" . | nindent 4 }}
spec:
  selector:
    name: ta-authenticator
  ports:
  - name: auth
    port: 80
    targetPort: auth
